name: Teste de unidade Java

on:
  push:
    branches: [ master ]

jobs:
  teste-unidade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Java 17.x
        uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          cache: maven
      - name: Build with Maven
        run: mvn clean install


